# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b1f588e4b291e652c3268cecbc73b9678e221358a80912c496b35766126a43fc5c48eb37e4df88e94890eeb8f50368abbf29276d316e2c58041f48952f189d0

test:
  secret_key_base: df019ebc10e8ca42e65d3705ff4bead0aedc1b354dd4c29e998936e26b4b67d2387d3ce5d947b2d7f399f6863e102c057f8a0159a9eff21ecebe0334152b6dba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
