# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 577eceb644463f0568362e4ea824a692c8113f72c4566f7358f94f45ac825df520e3b9bb3d0099a70d3070d9a1970e957bf0c20532713a7f80d19a9348ed5e94

test:
  secret_key_base: 26fe4b5ba814d07587a6585e2bd48c126b9222033f806588e4ca232d73e53500909841ad28e37aa02196c38201773b5c940bea9ed30a19404dc5504e49fe1ba5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
